project:
  type: book
  output-dir: docs

book:
  title: "Climate Change Data Visualization"
  author: "Colton Gearhart"
  date: "9/27/2023"
  cover-image: climate-dataviz.png
  chapters:
    - index.qmd
    #- data-collection.qmd
    - visualizations.qmd
    - report.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: flatly
    code-link: true
    code-fold: show
    code-tools: true
    code-block-border-left: "#2C3E50"
    highlight-style: github
    
title-block-banner: true
